import json
import logging
import os

import ollama

from backend.schemas.llm_analysis_schema import (
    LLMAnalysisResponse,
    ColumnLLMAnalysis,
)
from backend.services.ollama_client import (
    ensure_ollama_ready,
)
from backend.services.smart_column_filter import (
    is_obvious_column,
    heuristic_column_analysis,
)
from backend.utils.action_validator import validate_action

logger = logging.getLogger(__name__)

MODEL_NAME = os.getenv("OLLAMA_MODEL", "qwen2.5:1.5b")
OLLAMA_HOST = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434").rstrip("/")

BATCH_SIZE = 20


SYSTEM_PROMPT = """
You analyze dataset columns for synthetic data generation.

For EVERY input column, return exactly one result with:
1. is_identifier (bool)
2. action: keep | remove | new_id | generalize | derived | llm
3. reason: short explanation (max 10 words)

Rules:
- keep = generate column normally
- remove = exclude from synthetic data (e.g. high nulls, useless)
- new_id = column is an identifier; generate new synthetic IDs
- generalize = reduce detail (e.g. exact address → region)
- derived = computed from other columns
- llm = free-form text/string that should be generated by the local LLM
  (text, feedback, comments, reviews, descriptions, complaints, remarks, messages)

A unique column is NOT automatically an identifier.
Base your decision on dtype, sample_values, null_ratio, and unique_ratio.

Return exactly one entry per input column. Do not skip columns.
Keep reasons under 10 words.
"""


def _call_llm_for_batch(batch: list[dict]) -> LLMAnalysisResponse:
    """One LLM call for a small batch of column profiles with graceful heuristic fallback."""

    user_prompt = (
        "Analyze these columns. Return one result per column.\n\n"
        + json.dumps(batch, indent=2, default=str)
    )

    try:
        ensure_ollama_ready(model=MODEL_NAME, base_url=OLLAMA_HOST)

        client = ollama.Client(host=OLLAMA_HOST)
        response = client.chat(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            format=LLMAnalysisResponse.model_json_schema(),
            think=False,
            options={
                "num_ctx": 4096,
                "temperature": 0,
                "num_predict": 2048,
                "top_k": 10,
                "top_p": 0.9,
            },
        )

        parsed = LLMAnalysisResponse.model_validate_json(
            response["message"]["content"]
        )

        # Normalize actions & identifier consistency
        for col in parsed.columns:
            try:
                col.action = validate_action(col.action)
            except Exception:
                col.action = "keep"

            if col.action == "new_id":
                col.is_identifier = True
            elif col.action == "llm":
                col.is_identifier = False

        return parsed

    except Exception as error:
        logger.warning(
            "LLM batch analysis call failed (%s); using intelligent rule-based classifier.",
            error,
        )
        fallback_columns = [
            ColumnLLMAnalysis(**heuristic_column_analysis(profile))
            for profile in batch
        ]
        return LLMAnalysisResponse(columns=fallback_columns)


def analyze_columns(
    column_profiles: list[dict],
    progress_callback=None,
) -> LLMAnalysisResponse:
    """
    Hybrid approach:
      1. Rule-based pre-classification for obvious columns (fast)
      2. LLM analysis (with automatic fallback) for the rest (smart & resilient)
    """

    if not column_profiles:
        raise ValueError("No column profiles provided.")

    # ---------------------------------------------------------
    # STEP 1: Rule-based filter
    # ---------------------------------------------------------
    quick_results: list[ColumnLLMAnalysis] = []
    llm_profiles: list[dict] = []

    for profile in column_profiles:
        quick = is_obvious_column(profile)
        if quick is not None:
            quick_results.append(ColumnLLMAnalysis(**quick))
        else:
            llm_profiles.append(profile)

    logger.info(
        "[analysis] total=%d  rule-based=%d  to LLM=%d",
        len(column_profiles),
        len(quick_results),
        len(llm_profiles),
    )

    # ---------------------------------------------------------
    # STEP 2: LLM on remaining columns only
    # ---------------------------------------------------------
    llm_results: list[ColumnLLMAnalysis] = []

    if llm_profiles:
        total_batches = (
            len(llm_profiles) + BATCH_SIZE - 1
        ) // BATCH_SIZE

        for i in range(total_batches):
            start = i * BATCH_SIZE
            end = start + BATCH_SIZE
            batch = llm_profiles[start:end]

            parsed = _call_llm_for_batch(batch)
            llm_results.extend(parsed.columns)

            if progress_callback:
                progress_callback(i + 1, total_batches)

    # ---------------------------------------------------------
    # STEP 3: Merge (in original order)
    # ---------------------------------------------------------
    by_name = {c.column_name: c for c in quick_results}
    by_name.update({c.column_name: c for c in llm_results})

    ordered = [
        by_name[p["column_name"]]
        for p in column_profiles
        if p["column_name"] in by_name
    ]

    # Ensure any missing column profile is filled with fallback
    if len(ordered) < len(column_profiles):
        existing_names = {c.column_name for c in ordered}
        for p in column_profiles:
            if p["column_name"] not in existing_names:
                ordered.append(ColumnLLMAnalysis(**heuristic_column_analysis(p)))

    return LLMAnalysisResponse(columns=ordered)